

name: ci
on:
  pull_request:
    branches: ["main", "master"]

jobs:
  call-worflow:
    uses: studiographene/github-action-workflows/.github/workflows/checkov-terraform-iac-scan.yml@master 
    secrets: inherit

